### ISSUE TITLE
Maven Build Compilation Errors

### ISSUE THREAD

**Issue by SeBrul** [matsim-scenarios/matsim-sweden#4]
[log.txt](https://github.com/matsim-scenarios/matsim-sweden/files/5953203/log.txt)
Hello MATSim team,

I'm currently trying to get the matsim-sweden scenario to work, unfortunately, I'm running into several errors while compiling, for which I can't find any solutions at the moment. I have taken the following steps so far:

After cloning (master) and loading the project in maven I first got: 
```javascript
Error Could not find artifact org.matsim.vsp:vsp-playgrounds:pom:12.0-SNAPSHOT in matsim (https://dl.bintray.com/matsim/matsim)
```

Therefore I manually loaded and installed the latest version (`<vsp-12.0-20190909.151757-120.jar>`) from https://packagecloud.io/matsim-vsp/vsp-playgrounds.

After that the Maven project is loading its dependecies without errors, however, when compiling the Maven project I get several errors among others in SamplePopulation.java script (l.64): 
```javascript
cannot find symbol  symbol:   method getPersonAttributes()
```
When I trace back the calls in PopulationUtils.class and PopulationImpls.class I can't find a cause raise for that. But also in CreateLongDistanceDemand.java (l.142) I receive the error: 
```javascript
bad operand types for binary operator '+'
```
here I, unfortunately, can't find a cause either.

I also tried to compile an older version of the project (`<vsp-12.0-20190519.073153-20>`) to use a snapshot version from the time when the commit `<update matsim-maas to 12.0-SNAPSHOT>` was pushed to the matsim-sweden repo. Unluckily, this also didn't solve the problem and I still get the same errors.

Any ideas on how I could proceed further? I have attached the section of the log file with the errors (log.txt). Thank you very much in advance.

Kind regards
Sebastian

**Comment by jfbischoff** [comment]
Oh, probably the model should not be run with the 12.0-SNAPSHOT, but on a stable weekly release from May 2019. I will try to fix the pom in the coming days.

**Comment by kainagel** [comment]
I started with this before Joschka replied.  It is now running with the 12.0 release.  I can't say, however, if it is producing plausible results.  

Some of the adaptations I can remember:
* adapt to new way to handle time (probably not a problem)
* adapt to new way to handle subpopulation attributes (feels correct)
* explicitly bind missing raptor stop finder (feels correct)
* comment out switches in config.xml which do no longer exist (feels correct)

If this produces incorrect results, then what @jfbischoff proposes may be the quicker path to success.

**Comment by SeBrul** [comment]
Excellent, thank you very much for the quick feedback and changes. With the latest commit I was able to successfully compile the scenario. If I find anything strange in the outputs I will have a look at the 0.11.0-SNAPSHOT as a reference.

Thanks again for the great and fast help!
